Buildit
arjorb/buildit pull request #1
Opened 2022-11-27 11:30 UTC by arjorb

I am requesting for code review

2022-11-27 22:04 UTC, Stevenkwizera06 approved these changes
Nice work john

2022-11-27 22:04 UTC, Stevenkwizera06 commented on components/home/Properties.js
> +            <Button name='Explore' />
work on this button

2022-11-28 06:30 UTC, MugaboDenys requested changes

2022-11-28 06:30 UTC, MugaboDenys commented on components/about/Card.js
> +      <div className='w-[250px] h-auto bg-steelBlue-50 shadow-2xl shadow-blue-300 rounded-md'>
You're Still remaining with albitrary values like here

2022-11-29 20:19 UTC, Morrism1 approved these changes
LGTM!

2022-11-30 06:25 UTC, merged